spring:
  data:
    mongodb:
      dataetl:
        authentication-database: admin
        host: 10.50.125.142
        port: 27017
        username: root
        password: 123456
        database: data-etl
      detection:
        authentication-database: admin
        host: 10.50.125.142
        port: 27017
        username: root
        password: 123456
        database: detection
  kafka:
    bootstrap-servers: 10.50.125.141:9092
    producer:
      retries: 3
      retry-backoff-ms: 60000
      linger-ms: 1
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#logging:
#  level:
#    root: info
#    org.apache.spark: WARN
#    org.spark-project: WARN
#    org.apache.hadoop: WARN
#    org.spark_project.jetty: WARN
#    com.alibaba.nacos: WARN
#    org.springframework.boot: WARN
#    org.mongodb.driver: WARN

mysql:
  url: jdbc:mysql://10.50.125.141:3306/%s?useSSL=false&&characterEncoding=utf8&serverTimezone=GMT%%2B8
  username: root
  password: hxc@069.root_mysql
  driver: com.mysql.cj.jdbc.Driver

mongodb:
  data-etl: mongodb://root:123456@10.50.125.142:27017/data-etl?authSource=admin&authMechanism=SCRAM-SHA-256
  data-lake: mongodb://root:123456@10.50.125.142:27017/datalake?authSource=admin&authMechanism=SCRAM-SHA-256
  detection: mongodb://root:123456@10.50.125.142:27017/detection?authSource=admin&authMechanism=SCRAM-SHA-256
catalog:
  catalog-url: jdbc:mysql://10.50.125.141
  catalog-user: root
  catalog-password: hxc@069.root_mysql
  catalog-driver: com.mysql.cj.jdbc.Driver
spark:
  master: local[*]
  batch-size: 1000
  num-executors:

#shardingsphere的数据库配置
#shardingsphere:
#  datasource:
#    # 数据源公共参数
#    common:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      # 分表个数
#      sharding-count: 4
#    names: ds0,ds1
#    ds0:
#      jdbc-url: jdbc:mysql://192.168.238.129:3307/gmall_ums?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root
#    ds1:
#      jdbc-url: jdbc:mysql://192.168.238.129:3316/gmall_ums?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root

